//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Target_Report
{


    public partial class DailySalesEntry
    {

        protected global::System.Web.UI.WebControls.Panel pnlToast;

        protected global::System.Web.UI.WebControls.Literal litToastTitle;

        protected global::System.Web.UI.WebControls.Literal litToastText;

        protected global::System.Web.UI.WebControls.DropDownList ddlPartner;

        protected global::System.Web.UI.WebControls.Panel pnlEntryForm;

        protected global::System.Web.UI.WebControls.TextBox txtDailySale;

        protected global::System.Web.UI.WebControls.RegularExpressionValidator revDailySale;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDailySale;

        protected global::System.Web.UI.WebControls.TextBox txtTargetBalance;

        protected global::System.Web.UI.WebControls.ValidationSummary vsSale;

        protected global::System.Web.UI.WebControls.Button btnSave;

        protected global::System.Web.UI.WebControls.Button btnClear;

        protected global::System.Web.UI.WebControls.TextBox txtPartnerNameFollow;

        protected global::System.Web.UI.WebControls.TextBox txtContactNumber;

        protected global::System.Web.UI.WebControls.TextBox txtFollowDate;

        protected global::System.Web.UI.WebControls.TextBox txtRemark;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvRemark;

        protected global::System.Web.UI.WebControls.RegularExpressionValidator revRemark;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFollowDate;

        protected global::System.Web.UI.WebControls.Button btnSaveFollowup;

        protected global::System.Web.UI.WebControls.GridView gvTodaySales;

        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        protected global::System.Web.UI.WebControls.Button btnSearch;

        protected global::System.Web.UI.WebControls.Button btnResetSearch;

        protected global::System.Web.UI.WebControls.GridView gvMonthSales;
    }
}
